% Solve a Pattern Recognition Problem with a Neural Network
% Script generated by NPRTOOL
% Created Fri Apr 17 13:48:52 EEST 2014
% NURAY CAN %
% This script assumes these variables are defined:
%
%   azip - input data.
%   target - target data.
 
x = azip;
t = target;
 
% Create a Pattern Recognition Network
hiddenLayerSize = 10; % 10 neuron for hidden layer
net = patternnet(hiddenLayerSize);
 
 
% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100; %we can change these values net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;
 
 
% Train the Network
[net,tr] = train(net,x,t); 
 
% Test the Network
y = net(x);
e = gsubtract(t,y);
tind = vec2ind(t);
yind = vec2ind(y);
percentErrors = sum(tind ~= yind)/numel(tind);
performance = perform(net,t,y)
 
% View the Network
view(net)
 
% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotconfusion(t,y)
%figure, plotroc(t,y)
%figure, ploterrhist(e)
